# Generated by Django 5.1.7 on 2026-03-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='expiry_reminder_days_before',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='gym',
            name='interakt_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='interakt_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gym',
            name='wa_template_expired',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='wa_template_expires_today',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gym',
            name='wa_template_expiring_soon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
