# Generated by Django 5.1.7 on 2026-03-07 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_gym_expiry_reminder_days_before_gym_interakt_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapplog',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('template_name', models.CharField(max_length=100)),
                ('message_type', models.CharField(choices=[('expiring_soon', 'Expiring Soon'), ('expires_today', 'Expires Today'), ('expired', 'Expired')], max_length=30)),
                ('interakt_message_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('callback_data', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wa_logs', to='frontend.gym')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_logs', to='frontend.member')),
            ],
        ),
    ]
