# Generated by Django 5.1.7 on 2026-03-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_member_dob_alter_branch_id_alter_enquiry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='birthday_reminder_days_before',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='gym',
            name='wa_template_birthday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
