# Generated by Django 5.1.7 on 2026-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0022_gym_birthday_reminder_days_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='wa_template_birthday_today',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
