# Generated by Django 5.1.7 on 2026-03-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_gym_wa_template_birthday_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='Auto_archive_In',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
