# Generated by Django 5.1.7 on 2026-03-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_gym_auto_archive_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='Auto_archive_enable',
            field=models.BooleanField(default=False),
        ),
    ]
