# Generated by Django 5.1.7 on 2026-03-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_gym_auto_archive_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='subscription_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], default='basic', max_length=20),
        ),
    ]
