# Generated by Django 5.1.7 on 2026-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_gym_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='admission_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
