# Generated by Django 5.1.7 on 2026-03-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_member_admission_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='admission_start_number',
            field=models.IntegerField(default=1),
        ),
    ]
