# Generated by Django 5.1.7 on 2026-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_gym_admission_start_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admission_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
