# Generated by Django 5.1.7 on 2026-03-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_alter_member_admission_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='admission_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('gym', 'admission_number')},
        ),
    ]
